version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: mphmmm
      POSTGRES_PASSWORD: Matkhau123_
      POSTGRES_DB: SystemDesign
    ports:
      - "1605:2610"
    volumes:
      - pgdata:/var/lib/postgresql/data
  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=admin;Password=StrongPassword123;Database=userdb
    depends_on:
      - postgres

volumes:
  pgdata:
